- Source/Core.swift
Otherwise, rows in a hidden section can cause this to throw if the row's
hidden status changes, as the section won't have an index while hidden.
> Optionally unwrap section index, closes #45

- Example/Example/ViewController.swift
- README.md
- Source/Cells.swift
- Source/Rows.swift
- Tests/BaseEurekaTests.swift
- Tests/CollectionTests.swift
- Tests/HelperMethodTests.swift
As created for XLForm in https://github.com/xmartlabs/XLForm/commit/23b93a1a70bb17b8f2f65a4164978b6ac1190d9e this adds the ZipCode row type.
Example also added :+1:
> Add ZipCodeRow cell type

- Source/Core.swift
- Tests/BaseEurekaTests.swift
In `FormDelegate.rowValueHasBeenChanged`, `oldValue` and `newValue` are optional and it is easiest to work with optional value to differentiate set/update/delete.
> Change oldValue and newValue type to Any?

- Source/Core.swift
Using an optional Float instead of default value 0.0 to prevent collision with default tableView's bottom inset
> Fixed issue with tableVIew's bottom inset when keyboard is dismissed

- Source/Cells.swift
Modified observeValueForKeyPath function on _FieldCell and SegmentedCell to correctly update constraints
> Fix constraints update on _FieldCell and SegmentedCell

- Source/Cells.swift
I think it would be necessary to disable autocorrection and autocapitalisation in URLRow() by default.
> Disable autocorrection and autocapitalization in URLRow()

- Source/Cells.swift
Fixed bug where the TextViewCell's placeholderLabel did not line up with the textView's content.
To see an example of the issue, run the Example project and open the Native iOS Event Form. The last row entitled Notes has a placeholder, but when you start typing, the content does not line up with the placeholder's position.
A good writeup of the underlying problem and solution can be found here: http://stackoverflow.com/a/18987810/2712112
Before:
After:
> TextViewCell Placeholder/TextView Layout

- Source/Core.swift
Changed arrayData property to be a public let.
Backstory: I'm using Eureka in a project where I want to create my own custom selector controller. And when doing that it helps if I can access the arrayData property, as you do with SelectorViewController/MultipleSelectorViewController/SelectorAlertController/etc.
> Made arrayData public let

- Eureka.xcodeproj/project.pbxproj
- EurekaTests/ImageRowTests.swift
- Source/Rows.swift
Hi, I really appreciate the refactored `ImageRow` and the use of `ActionSheets`!
Looking at the source, I thought I can create an `ImageRow` like this:
```
<<< ImageRow(){
$0.title = "ImageRow"
$0.sourceTypes = [ImageRowSourceTypes.Camera, ImageRowSourceTypes.PhotoLibrary]
}
```
But this doesn't work. Xcode says "Type 'ImageRowSourceTypes' has no member 'Camera'".
I tried to change the options in `ImageRowSourceTypes` to public, but then the app crashes on the simulator with the message "Source type 1 not available".
This error appeared, because if an `OptionSetType` gets initialized with `0` it automatically referes to empty / `.None` (which is the case for `UIImagePickerControllerSourceType.PhotoLibrary`). This produced some weird behaviour, causing the crash described above. 
I changed …
> Fix image row source types

- Source/Core.swift
1. Add .Hidden observer
2. Add .Disabled observer
3. Then .Hidden observer is removed.
Find out working bug reproduction demo.
https://github.com/jechol/eureka-mixed-hidden-disabled-observer-bug-reproduce
> Fix a bug that removes existing observers when other type of observer is added

- Source/Controllers.swift
Unless I'm missing something, not declaring this initializers as public makes it extremely painful to subclass these controllers. This PR simply exposes the designated initializer as public, so subclasses can override initializers as necessary.
> Make ViewController Designated Initializers Public

- Source/Cells.swift
- Source/Core.swift
The PickerInlineRow always crashes when you close it while it is still spinning.
CountDownInlineRow also, but less often.
Added a teardown() function on the Cell to remove delegates from pickers and cleanup addTarget(self) references.
teardown() is called when the Row is deinitialised, it is the opposite of setup()
> Add teardown() to Cell to clean up delegates and targets.

- Source/Core.swift
Fix crash issue: row.baseCell.cellBecomeFirstResponder() may be cause InlineRow collapsed then section count will be changed. Use orignal indexPath will out of  section's bounds.
> Fix crash issue:  The section contains InlineRow and FieldRow, expand Inline and select FieldRow's titleLabel will crash.

- README.md
Seeing as it is such a common requirement, I though it would be good to move the instructions for retrieving form values to the `Usage` section.
> Move "How to get the form values" section to "Usage"

- Eureka.podspec
The `source_files` option wasn't changed after the restructure in #290.
> Update `source_files` in `Eureka.podspec`

- Source/Core/Core.swift
Closes https://github.com/xmartlabs/Eureka/issues/405
> Better row deselection behavior during interactive transitions

- Source/Rows/SegmentedRow.swift
This solves a constraint resolution issue that can appear when reloading cells. Having the hugging priority of the label and the segmented control both equal 500 makes the layout engine choose different views at different times (initial load vs. cell reload for example). 
Reducing the hugging priority of the segmented control allows it to fill the remaining space more egearly than it's peers.
My rationale for reducing the content hugging priority of the segmented control is the default appearance of the demo (and my own forms) initially appear after load with the segmented control taking over the spare space beyond it's initial width constraint (see screenshot). 
closes xmartlabs/Eureka#478
> Reduce content hugging priority of UISegmentedControl inside SegmentedRow

- Source/Rows/Common/GenericMultipleSelectorRow.swift
Just added a sort() on the display values so now there is a pattern on the results, as it uses Set, before this change the values shown were not sorted in any way. 
More details can be found on: http://stackoverflow.com/questions/37597870/
> Fix lack of sort on display value for GenericMultipleSelectorRow

- Source/Core/BaseRow.swift
- Source/Core/Core.swift
- Source/Core/Row.swift
Fixed a typo. Potentially breaks backwards compatibility for 1.6.x users (compiler error), so might want to defer merging til a 2.x release.
> Rename hightlightCell to highlightCell. (Remove extra 't'.)

- Example/Example/ViewController.swift
- Source/Core/SelectableSection.swift
- Source/Rows/Controllers/SelectorViewController.swift
onSelectSelectableRow will not be called when nothing changes
(when `enableDeselection = false` and user deselects a row)
Added enableDeselection customisation parameter to SelectorViewController
> Deselection changes

- Source/Core/Core.swift
Hi,
For a specific project I need to create an equivalent of `GenericMultipleSelectorRow` with specific features.
However I can't access to the `presentationMode?.completionHandler` because it is internal. So I just make the `completionHandler` public in order to have access to this property outside the Eureka framework.
Best,
Yannick
> Make `completionHandler` public in PresentationMode for subclassing purpose

- Source/Rows/ImageRow.swift
Right now when using the clear action on an ImageRow only the value of the row is set to nil. The property imageURL should also be resetted.
> Also clear imageURL when clearing the row

- Source/Rows/StepperRow.swift
Stepper row wasn't updating the controls when changing the value from setValues(values: [String: Any?]). I moved the UI update code from the cell setup code to the cell update code and now it works as intended (in my opinion at least, other rows has this behaviour as well). I believe it's already covered by test cases.
> (StepperRow) Moved stepper and valueLabel update code from setup() to update()

- Source/Core/BaseRow.swift
- Source/Core/Form.swift
- Source/Core/Row.swift
- Tests/CallbacksTests.swift
- Tests/HiddenRowsTests.swift
Changed internal variables `tagToValues` to be [String: Any] as values are Any and NSPredicates require Any. No need to cast to `AnyObject` anymore
If the value of a row is nil, we now insert `NSNull()` into this dictionary
@xmartlabs/eureka
> Fix predicate evaluation when values include Optional and or nil

- Source/Core/Core.swift
Everything is told in the title.
In the swift2.2 branch the `PresentationMode.completionHandler` property is public while in the swift2.3 no.
I need this property to be public for my project that I updated to Swift2.3 waiting for the Swift3 migration of all the dependencies.
> Make the PresentationMode.completionHandler public like in the Swift2.2 branch

- Eureka.xcodeproj/project.pbxproj
- Source/Core/BaseRow.swift
- Source/Core/Row.swift
- Source/Rows/Common/SelectorRow.swift
Hi,
This pull request just aims to open some classes and methods in order to be able to subclass them properly. For example for the `Row` class I've opened the `customDidSelect` and `customUpdateCell ` methods.
> Change the access control to open for some classes and methods

- Source/Core/Core.swift
In swift2 version of eureka we can override this methods for custom logic. This pull request returns those opportunities.
> Changing access level of keyboardWillShow and keyboardWillHide methods

- Eureka.xcodeproj/project.pbxproj
Provisioning style 'Automatic' is the most consumer friendly provisioning style for frameworks. It permits the host project to dictate the provisioning style. 
Otherwise if a host project specifies Manual provisioning style, xcodebuild will fail when attempting to compile the subproject with: 
> Eureka does not support provisioning profiles. Eureka does not support provisioning profiles, but provisioning profile <defined provisioning profile> has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.
> Convert ProvisioningStyle to Automatic

- README.md
Example code used undeclared variable `ruleSet`
> Fix variable name in README

- Source/Core/Core.swift
use workaround issued in #783.
> Fix UINavigationController interactive pop gesture could cause navbar blink and toolbar animation interruption

- Source/Validations/RuleRegExp.swift
Someone forgot to set `self.allowsEmpty` in the initializer
> Set RuleRegExp.allowsEmpty

- Source/Rows/Controllers/MultipleSelectorViewController.swift
- Source/Rows/Controllers/SelectorViewController.swift
Use case scenario: user implements custom selector controller as subclass of `SelectorViewController` for `PushRow` and wishes to instantiate it from a storyboard with a segue transition or a xib. But because of `fatalError` in `init(coder:)` for `SelectorViewController` it is not possible. Segue presentation mode will lead to crash, what was not happening in 1.7.0 release.
I can understand the reasoning for not calling `fatalError` for rows as they are designed to be instantiated from code, but for view controller I don't see reason not to allow to instantiate them from storyboards or xibs. `FormViewController` does not follow that behavior. If there are strong reason for not allowing that that should be stated in the docs and probably segue presentation style should be deprecated for …
> Removed fatalError from init(coder:) for selector view controllers

- Source/Rows/ActionSheetRow.swift
- Source/Rows/ButtonRow.swift
- Source/Rows/CheckRow.swift
- Source/Rows/Common/DateInlineFieldRow.swift
- Source/Rows/Common/SelectorRow.swift
- Source/Rows/LabelRow.swift
- Source/Rows/PickerInlineRow.swift
- Source/Rows/SelectableRows/ListCheckRow.swift
- Source/Rows/SwitchRow.swift
**The problem**
I've created a custom cell by:
- implementing a cell class that inherits `ButtonCellOf`
- implementing a row class that inherits from `Eureka._ButtonRowOf`
The row class instantiates `CellProvider` and passes a NIB name.
Now, this used to work fine in Eureka 1.7. However, after I updated to the latest Swift 3 master, the following problem has arisen:
- my custom cell implementation wouldn't compile unless `init?(coder: NSCoder)` was implemented
- when I've implemented it by calling `init?(coder: NSCoder)` on `super`, the app has started to crash.
**The solution**
I think that the problem exists because `init?(coder: NSCoder)` in `ButtonCellOf` calls `fatalError` instead of calling `init` on `super`. I suspect that it has been introduced while migrating to Swift 3. This …
> Implement init?(coder: NSCoder) for some cell types

- Source/Core/Core.swift
This allows us to change the form of a view controller which is not being displayed at the moment but will be displayed. Sometimes this would throw an UITableView Inconsistency exception.
There seem to be no negative side effects.
> Reload the tableView even if it is not added to a window

- Source/Core/Core.swift
Fixes issue: https://github.com/xmartlabs/Eureka/issues/886
> adds 'cell.row.wasChanged' to check for cell validation

- Source/Rows/SliderRow.swift
I removed justLabelConstraints from addConstraints(), since it is never used and not necessary. I restructured the function accordingly. [I know this is a small change, but this is my first pull request and contribution to an open source project ever, so please be nice, if I did anything wrong :)]
> cleaned up addConstraints() inSliderRow.swift

- Example/Example/ViewController.swift
- Source/Core/SelectableSection.swift
- Source/Rows/Controllers/SelectorViewController.swift
This PR reverts some of the changes made in #551 and adds two new properties for better control of dismissing `SelectorViewController`. Please see [this](https://github.com/xmartlabs/Eureka/pull/551#issuecomment-262821225) and [this](https://github.com/xmartlabs/Eureka/issues/261#issuecomment-274661489) comments for some reasoning.
> Always call onSelectSelectableRow, added properties to control selector vc dismissal

- Source/Core/Core.swift
Removing the forced navigationAccessoryView.tintColor set to be able to use with the Appearance Proxy.
NavigationAccessoryView.appearance().tintColor = 
NavigationAccessoryView.appearance().barTintColor = UIColor(...)
> Removing the forced navigationAccessoryView.tintColor set

- README.md
Whitespace messes up GitHub's ability to properly render HTML, resulting in many sections of the REAME printing html to screen.
> Update README html to render correctly on GitHub

- README.md
It's not working anymore (probably a leftover in the doc)
> Update README (remove section header string literal

- Example/Example/CustomRows/ImageRow/ImageRow.swift
When an `imageRow` is in a `MultivaluedSection` the image isn't showed because the reorder control takes the `accesoryView`'s place.
In these changes the image is also set to the `editingAccesoryView` so that it is always shown, even when the `tableView` is in edit mode.
> Fixes #977

- Eureka.xcodeproj/project.pbxproj
- Source/Core/BaseRow.swift
- Source/Core/Form.swift
- Source/Core/Section.swift
- Tests/RowsInsertionTests.swift
- Tests/SectionsInsertionTests.swift
How it's pointed out in this issue #1024, if either sections or rows are added to the form using subscripts then they wont be correctly handled. For example `form[0][0].reload()` won't work if the rows was added in this way `form[0][0] = SomeRow()`
The changes fix how the sections and rows are inserted into the form, key points are:
* add sections and rows to `_allSections` and `_allRows` respectively
* call `wasAddedTo()` to each section and row added
* call `willBeRemovedFromForm` to each of the section and row that are being replaced.
Previous changes made subscripts works in the same way that `append` does
Fixes #1024
> Fixed how sections and row are inserted using subscripts

- Source/Rows/SliderRow.swift
Fixes the issue #942. The slider was not being disabled when the `SliderRow` was set disabled. This was due to the missing check if the row is disabled in the cell update
> Fixed #942

- Source/Core/Section.swift
This should fix #1082, I've tried running the example app on an iOS 11 beta device and it all seemed to be working properly.
I could not run the app or the unit tests on the simulator due to an Xcode problem though.
> Fixed array slice for Swift 3.2

- Source/Core/SelectableSection.swift
It seems that `filter` creates a new and appends objects in there. In the case of filtering in a Section it creates a new `Section` and calls `append` which in turn calls a lot of functions that should not be called when filtering a Section. This changes fix some breakages.
Weird is that calling filter on a Section from a View Controller does not break anything (does not call `append` either) so that the issue might be only related to concretely casted SelectableSection's
> Fix SelectableSection issue with filter

- Source/Rows/Common/FieldRow.swift
- Source/Rows/SegmentedRow.swift
- Source/Rows/SliderRow.swift
Fixes #1109 
When the system font size is changed, the UITableViewCell's create a new `textLabel` and `detailTextLabel`, so the pointer stored in the SegmentedRow is outdated. The issue crash is caused due to the original textLabel is removed from its superview and a new label is added.
* Fixed an issue with the SliderRow, where the app wasn't crashing but text labels were duplicated. Checkout the GIF below. Instead of adding again the original labels, the proposed change updates the labels pointing to the new ones
* SliderRow issue:
* Solved:
@xmartlabs/eureka
> Updating labels after changing system font size

- Source/Core/Row.swift
Validating on demand should ONLY validate when u demand it and not, like it is now, always when something changes. I need this in a concrete project because I get strange validation behaviour if it validates all the time.
> change validation on demand behaviour when row was not valid

- Source/Core/Core.swift
Removing the observers in `viewDidDisappear` leads to an issue with the interactive dismissal of `UIViewController`s.
When the interactive dismissal begins, `viewWillDisappear` is called and then, if the gesture in cancelled, `viewWillAppear` and `viewDidAppear` are called again but not `viewDidDisappear`.
This way, every time a dismissal is cancelled a new observer is added without removing the previous one. This results in multiple calls to `keyboardWillShow/Hide` when the keyboard is presented/dismissed.
Moving the `removeObserver` calls to `viewWillDisappear` should fix the issue.
> Remove observers in viewWillDisappear

- Example/Example/ViewController.swift
The example project implements a currency formatter. It works very well most of the time.
Consider the following scenario:
The user has a European locale with the € currency.
Numbers are formatted the following way: 12,43 €
When the user taps into the currency style row in the example, the cursor is placed after the € sign.
The way the formatter currently works, the user can not delete any number from that location. He has to manually move the cursor to some position before the € sign. 
The code in this PR checks if the last sign is the current currency sign and if it is missing from the edited string. Then he deletes the last number.
> Improve currency formatter

- Source/Rows/SliderRow.swift
Changes the SliderRow's layout constraint to be aligned relative to the cell's margins. This makes the subviews present in the SliderRow to have the same horizontal margins that the labels from UITableViewCell.
This fixes #1127.
-- Edited --
<table>
<thead>
<tr>
<th>iPhone SE</th>
<th>iPhone 7</th>
<th>iPhone 7 Plus</th>
</tr>
</teadh>
<tr>
<td><img src="https://user-images.githubusercontent.com/4791678/28648658-be31ac0e-7245-11e7-8e97-17cbfa41f85f.png" /></td>
<td><img src="https://user-images.githubusercontent.com/4791678/28648710-17e06812-7246-11e7-823e-c0a491000760.png" /></td>
<td><img src="https://user-images.githubusercontent.com/4791678/28648686-eb43cda8-7245-11e7-9dbb-2901a6e97073.png" /></td>
</tr>
</table>
> Fix SliderRow horizontal margins

- Example/Example/ViewController.swift
- Source/Core/SelectableSection.swift
Resolves #1218 
In Swift 4 `filter` method called in this case has a [new](https://github.com/apple/swift-evolution/blob/master/proposals/0174-filter-range-replaceable.md) behaviour. Implementation of `RangeReplaceableCollection.filter` creates new array of the same type (`SelectableSection`) by calling `init` (can be checked by adding breakpoint at `SelectableSection.init` method) and then calling `append(contentsOf:)` method, which results in adding previously selected row (only this row will have non-nil value) to this section and so overriding a reference to it from `self` (in this scope).
So basically what happens is that every time raw is selected it creates new section with just this row. Then when we leave the stack this section is being deallocated as it is not referenced …
> fixed deallocating section

- Source/Core/Helpers.swift
- Source/Core/Section.swift
- Source/Rows/Common/GenericMultipleSelectorRow.swift
- Source/Rows/MultipleSelectorRow.swift
Fixes https://github.com/xmartlabs/Eureka/issues/1178
As described in the issue above, it would be great to support both the Swift 3.1 and 3.2 compilers, at least for a little while since people will slowly transition from Xcode 8 to Xcode 9. When merged, this will allow people to develop for iOS 11 on the Xcode 9 betas all while publishing with Xcode 8 or AppCode.
Summary of changes:
- Added back the old signature for `replaceSubrange` in `Section` and put it behind a version check. I'm not sure if there's a way to consolidate the code between the swift 3.1/3.2 methods so I'm open to suggestions.
- Added a `_ImplicitlyHashable` type which works around a warning in the 3.2 compiler for redundant generic constraints. The workaround is described [in the …
> Add support for Swift 3.1 in the Swift 3.2 branch

- Source/Rows/Common/FieldRow.swift
- Source/Rows/SegmentedRow.swift
- Source/Rows/SliderRow.swift
Hello,
It should fix the issue #1258 where the UILayoutPriority initialiser does not require to have rawValue anymore.
> Fixed UILayoutPriority initialisers

- Source/Core/Core.swift
I need to display section indices from a `SelectorViewController` subclass of mine, but since `FormViewController` doesn't have a default implementation for `sectionIndexTitles(for:)` and `tableView(_:, sectionForSectionIndexTitle:, at:)` my subclass's implementations are not called. This PR includes default implementations that do not affect the current behavior and don't attempt to display any section indices.
> Allow for FromViewController subclasses to display section indices

- Source/Validations/RuleRegExp.swift
- Tests/ValidationsTests.swift
I appended the regular expression pattern `([/?#]\\S*)?` to allow an optional query parameter (e.g. `?key=value&flag` and a location anchor (e.g. `#location`) at the end of the URL.
This also adds a basic test for the `RuleURL`.
Fixes #1239 
Note: The URL matcher could still be improved by using tested regular expressions like [these](https://mathiasbynens.be/demo/url-regex), but this seems to be science in itself.
> Fix regular expression for URLs to allow query and location parameter

- Eureka.xcodeproj/project.pbxproj
- Example/Example/ViewController.swift
- Source/Rows/ActionSheetRow.swift
- Source/Rows/AlertRow.swift
- Source/Rows/Common/AlertOptionsRow.swift
- Source/Rows/Controllers/SelectorAlertController.swift
These changes fixes the issue #1335 where changing the `SelectorAlertController.cancelTitle`'s value in some cases doesn't work because its value is used in the view did load callback.
* Add a new row type `AlertOptionsRow` used specifically for option rows that show an `UIAlertController`.
* `AlertOptionsRow` includes the property `cancelTitle` in order to change the cancel action's title within `UIActionController`.
* Deprecates `SelectorAlertController.cancelTitle` in favor of `AlertOptionsRow.cancelTitle`
> Setup alert controller cancel title from row

- Source/Rows/SegmentedRow.swift
Without that, we have crash for `SegmentedCell` with xib. Description of crash tells that we didn't call `super.updateConstraints()`
> Call super.updateConstraints in SegmentedCell

- Source/Core/Section.swift
It's crashing when 'index' is greater than number of sections of tableView.
> Crash prevent Section.swift

- Source/Rows/DatePickerRow.swift
Hi! Found an issue in rows that use UIDatePicker with mode == .countDownTimer. 
Steps to reproduce:
1. Run Examples app
2. Inline rows -> CountDownInlineRow
3. Try to choose 0h0m. UIDatePicker will automatically choose 0h1m(because UIDatePicker doesn't allow to choose 00:00 interval)
4. Choose 1h1m. 
Actual result: label with row value remains on 0h1m value, but UIDatePicker shows 1h1m.
Expected result: both label and UIDatePicker must have 1h1m value.
It turned out that it is a old UIDatePicker bug. I've just added workaround suggested in this [StackOverflow thread](https://stackoverflow.com/questions/20181980/uidatepicker-bug-uicontroleventvaluechanged-after-hitting-minimum-internal#comment56681891_20204225) and everything is working now.
> Add workaround for UIDatePicker bug when mode == .countDownTimer

- Source/Rows/Common/FieldRow.swift
In addition to #965 ...
I found that the force updating constraints introduced in #965 is useful also when `titlePercentage` is not customized.
Without forcing that, title label can overlap to its value label.
The issue reproduces when iOS perform re-layout titleLabel (with the fact that titleLabel refs to `UITableViewCell.textLabel`) without updating its constraints. This case may occur in swiping, showing alert or actionsheet from the same section.
In the Eureka Example, adding ActionSheetRow after TextRow and set a long title for the TextRow reproduce the issue on iOS 11 (including iOS 11.2).
> Fix FieldCell titleLabel layout can overlap to its value label

- Source/Core/SelectableSection.swift
From time to time it is helpful to have non-selectable rows like switch rows besides selectable rows (e.g. as inline rows). While this basically works, it fails when the selected row changes. In this case, also the values of the non-selectable rows are reset. With a little check this can be fixed.
> Allow non-selectable rows to exist besides selectable rows

- README.md
> Fixes example about getting rows by tag

- Source/Core/Core.swift
- Source/Rows/SliderRow.swift
The default rowHeight for UITableView is on 44.0. Set it to UITableViewAutomaticDimension.
Fixes #1400
> Support dynamic font size changes

- Source/Rows/Common/FieldRow.swift
Hey guys! First of all I would like to thank you all for the work you do! :D
**Case:**
Almost all row types in Eureka use a stock UIKit UITableViewCell as underlying cell. So if you change the UITableViewCellStyle of that cell if automatically changes the UI of the Eureka row.
But that are some rows that are backed by a custom Eureka row (FieldRow). So setting the UITableViewCellStyle of that cell doesn't affect the UI.
**Solution:**
I've changed the customConstraints method on FieldRow to change its layout if the row have a .subtitle style.
I develop in a way it doesn't modify the previous behaviour (keeping the same code). And just add an case for this new style.
The new layout code is very similar to the old one, so I guess its self explanatory.
We are using in production for some …
> Implements support for UITableViewCellStyleSubtitle on FieldRow

- Source/Rows/ActionSheetRow.swift
This is a really convenient place to subclass this row if you just want a custom UI, are we able to make it open please?
> allow ActionSheetRow to be subclassed

- Source/Core/SwipeActions.swift
We have to end the SwipeActions manually sice iOS 10 does not automatically handle this for us.
This fixes #1457.
> CompletionHandler for SwipeAction under iOS < 11

- Example.xcodeproj/project.pbxproj
- Example/EmojiCell.xib
- Example/Example/Controllers/RowsExample.swift
- Example/Example/CustomCells.swift
- README.md
- Source/Rows/Controllers/MultipleSelectorViewController.swift
- Source/Rows/Controllers/SelectorViewController.swift
Currently the functionality to specify a custom `CellProvider` or `cellStyle` to be used for a `SelectorViewController`s rows is broken.
A `CellProvider` / `cellStyle` may be set on the row using the `selectableRowCellSetup`'callback, however this does not work as this callback occurs *after the cell has already been created.*
To resolve this issue, another callback `selectableRowSetup` is proposed, that is fired after the row is created, but before the cell is created.
> add 'selectableRowSetup' callback to SelectorViewController & MultipleSelectorViewController

- Example/Example/Controllers/FieldRowCustomizationController.swift
- Source/Rows/TextAreaRow.swift
Based on this [issue](https://github.com/xmartlabs/Eureka/issues/41) I added the possibility for a scrollable read only textAreaRow. I also changed the Example app to show its implementation. Hope it helps!
> Implement readOnly textAreaRow feature

- Source/Core/Cell.swift
- Source/Rows/ButtonRow.swift
- Source/Rows/CheckRow.swift
- Source/Rows/SelectableRows/ListCheckRow.swift
- Source/Rows/StepperRow.swift
This is a do-over of #1439, which caused crashes reported #1447.
As in #1439 we update the row when the tint colour changes. This should capture all uses of `tintColor` in the various `update` methods throughout the framework.
This PR adds explicit detection of the potential for an infinite loop, which occurs when a cell changes its `tintColor` in the `update` method. This change is in `Cell.swift`.
This PR also removes all the instances where components _change_ the `tintColor` in their `update` method. I don't believe that our cells _should_ set their own `tintColor` as this prevents them from participating in the cascade of `tintColor` from their parent views. In `CheckRow.swift` and `ListCheckRow.swift` I have changed to using `tintAdjustmentMode`, which I believe is the correct way …
> Update cell when tintColor changes (without crashing)

- Eureka.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Example/Example/Controllers/MultivaluedExamples.swift
- Example/Example/Controllers/SwipeActionsController.swift
- README.md
- Source/Core/Core.swift
- Source/Core/Form.swift
This was changed with SwipeActions. 
`isEditing` is now being set in viewWillAppear (only first time) if there is a MultivaluedSection in the form (even if it is hidden)
Fixes #1478 
Fixes #1503
> Fix multivalued section isEditing setting

- Source/Rows/DoublePickerInputRow.swift
- Source/Rows/DoublePickerRow.swift
- Source/Rows/TriplePickerInputRow.swift
- Source/Rows/TriplePickerRow.swift
Added the ability to customize the display value for DoublePickerRow and TriplePickerRow.
Here's a usage example that mimics a date picker:
```swift
<<< TriplePickerRow<Int, Int, String> { row in
row.firstOptions = { Array(1...12) }
row.secondOptions = { _ in return Array(0...59) }
row.thirdOptions = { _,_ in return ["am", "pm"] }
row.displayValueForFirstRow = { a in return String(a) } // stringifies `a`
row.displayValueForSecondRow = { b in return String(format: "%02d", b) } // adds padding 0s if `b < 10`
row.displayValueForThirdRow = { c in return c.capitalized } // capitalizes `c`
row.value = Tuple3(a: 4, b: 5, c: "AM") // will display as 4 | 05 | AM
}
```
> Fix for issue #1490

- Source/Rows/PickerRow.swift
It would be very helpful to be able to customise the display of the UIPickerView used in PickerRows. Setting the background color is easy, but changing the text color is tricky. I came across the `UIPickerViewDelegate` function [`pickerView(_:attributedTitleForRow:forComponent:)`](https://developer.apple.com/documentation/uikit/uipickerviewdelegate/1614375-pickerview) which returns an `NSAttributedString` (which can specify color).
In my project which uses Eureka, I couldn't find any way that I could implement that function and reuse the existing PickerCell: I ended up having to duplicate the PickerCell / PickerRow code, and add the extra method to PickerCell. It would be very nice to have this customisation built-in, which is what this commit does.
I am using it in `defaultCellUpdate`; …
> Add ability to customise the text color of UIPickerView used by PickerRow

- Source/Core/Core.swift
- Source/Rows/DoublePickerRow.swift
- Source/Rows/TriplePickerRow.swift
The crash happens when you have one of these rows as inline rows andyou edit the picker's value and then collapse the inline row before the action takes place. This results in a delegate method called on the cell, when the row for that cell has possibly been deleted.
Fix #1587
> Fix crash with double and triple picker rows

- Source/Core/NavigationAccessoryView.swift
Fixes an issue where the images of the NavigationAccessoryView might not be loaded if it is subclassed.
> Chevron's must be loaded from Eureka's bundle

- Eureka.podspec
Projects that depend on Eureka and install xcode 10 run into
errors because they may still be building with swift language
version 4.1 which the Eureka pod will inherit (because it is not
otherwise specified) and then the Eureka pod fails to build
Cocoapods will respect this setting when generating targets so
as Eureka changes the specific swift version it targets this setting
should reflect that.
> Declare swift language version required in podspec

- Source/Core/Form.swift
This includes the possibility to validate e form without validating rows that are disabled. This is usefull for fields that are set by other fields input.
> Adding `includeDisabled` to validate form method

- Source/Rows/FieldsRow.swift
This PR sets [`textContentType`](https://developer.apple.com/documentation/uikit/uitextinputtraits/1649656-textcontenttype) to the correct values on `EmailCell`, `PasswordCell`, `URLCell` and `UsernameCell` which enables [password autofill](https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_a_text_input_view) as well as allowing the system to attempt to autofill values when possible. The property was introduced in iOS 10. `.username` and `.password` were only added in iOS 11.
> Set textContentType for relevant cells

- Source/Rows/SegmentedRow.swift
If you have a long title then set `cell.titleLabel?.numberOfLines = 0` and set an appropriate height.
> Avoid segmented row title label pushing value out of bounds

- Source/Core/Core.swift
Closes #1674 
Tested on iOS 12.0 and 11.4
> Fix #1674 by removing double `isEditing` switch

- Source/Core/Section.swift
This allows easier access to all the rows (including hidden) of a Section.
> Add `allRows` variable to Section

- Source/Core/Row.swift
- Tests/SetValuesTests.swift
Goal
===
The idea is to give the row the ability to reset its own value to a predefined **default**.
To do this, we create a new property to store the **default value**, that won't change along with it's **value**. Doing so, we allow the row to reset itself at anytime, since it knows its own default value.
The main idea was to create the possibility to do this in the whole `section` or `form`, just like setting the form to a default state. I couldn't find a way to do this as I didn't explore much. If you have any idea, feel free to suggest.
The main motivation was to make the code cleaner, and more understandable, as the row should be responsible for its values and the things related directly to it, in my opinion.
How to test
===
Run the `testSetDefaultValues` test.
> Allow the row to reset its own value

- Source/Rows/Common/FieldRow.swift
Not doing this could lead to memory leak (#1764)
Fixes #1764
> Deallocate pointers when formatting values in FieldRow

- Source/Core/Core.swift
Some times it may be need to disable scroll on displaying inlineRow
UITableView.ScrollPosition.none -> scroll tableview to bottom of cell =(
> Disable scroll on show inlineRow if position none 

- Source/Core/BaseRow.swift
- Source/Core/Core.swift
Reverts change in #1784 but allows to do that feature by setting nil to `destinationScrollPosition`
> Allow `.none` scrolling as well as no scroll when making row visible

- Source/Core/Form.swift
Observers were not being removed correctly
Fix #1804
> Correctly remove observers when rows are deleted

- Example/Example/Controllers/SwipeActionsController.swift
- README.md
- Source/Core/SwipeActions.swift
ContextualAction's `backgroundColor` was set to a computed properties with an empty setter and a getter that always returned `nil`.
Now it is changed to `actionBackgroundColor` which gets/sets `backgroundColor` for `UITableViewRowAction` and `UIContextualAction`
Fixes #1790
> Fix backgroundColor for SwipeActions

- Source/Core/BaseRow.swift
- Source/Core/Form.swift
- Source/Core/Row.swift
- Source/Core/RowType.swift
I did not read any contributing documents of any kind. I needed to solve a problem and solved it. Just decided to share the solution. I am open to providing tests/documentation, but wanted feedback first to see if this is an appropriate solution.
On #870 several suggestions were made to make it easier to tie a save button to validation results. I tried to solve this problem by extending Form and Row and BaseRow... etc. In the end I found it was too much private variables to do that way. So I went and added a "quietly" parameter to Form.validate and Row.validate.
Since this parameter defaults to false, I can't see how it would have any effect on normal usage.
I then use Form.validate(quietly: True) in onRowValidationChanged and in onChanged with a closure to update the ui save button.
This …
> added quietly parameter for use with non-ui validation

- Source/Validations/RuleLength.swift
RuleRequired manages those cases.
Fixes #1848
> RuleMinLenght (and others) should pass for nil and empty strings.

- Example/Example/Controllers/NativeEventExample.swift
Simple unimportant update to NativeEventExample enums to use CaseIterable instead of manually creating a static array property with all cases included.
> Simple unimportant update to example to use CaseIterable

- Source/Rows/TextAreaRow.swift
TextAreaRow does not conform to FieldRowConformance therefor formatter is ignored/not used in textViewDidChange()
Changed the check for FormatterConformance in textViewDidChange()
> Fixed TextAreaRow Formatter comformance check

- Source/Rows/Common/DecimalFormatter.swift
Building on Xcode 11 produces a pair of documentation warnings related to the documented parameter names on `DecimalFormatter.getObjectValue()`. This commit recreates the doc comment with Xcode's generated parameter names.
-----
The warning:
```
Documentation Issue Group
/Users/aaron/repos/obakit/Carthage/Build/iOS/Eureka.framework/Headers/Eureka-Swift.h:229:12: Parameter 'for' not found in the function declaration
/Users/aaron/repos/obakit/Carthage/Build/iOS/Eureka.framework/Headers/Eureka-Swift.h:231:12: Parameter 'range' not found in the function declaration
```
> Fixes documentation warning

- Example/Example/Controllers/MultivaluedExamples.swift
- Source/Core/Section.swift
- Source/Core/SelectableSection.swift
- Tests/MultivaluedSectionTests.swift
Under the hood, a `Section`'s header and footer can both be `nil`, but the available initializers do not allow you to specify `nil` values for these unless you use the zero-argument init method.
This change is backwards-compatible, and should not affect any existing code.
> Allows a section's header and footer to be `nil`

- Source/Core/BaseRow.swift
Fix for https://github.com/xmartlabs/Eureka/issues/1929
> Add [unowned self] to fix reference cycle

- Source/Core/Core.swift
UITableView will adjust it's `contentInset` with safe area. The adjusted `contentInset` can be derived from `adjustedContentInset` api. When table view is influenced by safe area, `Eureka 5.1.0` has an issue that `contentInset` is adjusted too much after keyboard shows.
Solve #1959 #1953
> Fix table view contentInset adjustment with safe area when keyboard shows

- Source/Core/Core.swift
The corresponding method is deprecated as of iOS 13 and emits a warning when building on iOS13 and greater projects.
This marks the method as deprecated and directs users to use the leading/trailing based API instead (which has already been implemented here).
Comment showing deprecation from `UIKit/UITableView.h`
```objc
// This method supersedes -tableView:titleForDeleteConfirmationButtonForRowAtIndexPath: if return value is non-nil
- (nullable NSArray<UITableViewRowAction *> *)tableView:(UITableView *)tableView editActionsForRowAtIndexPath:(NSIndexPath *)indexPath API_DEPRECATED_WITH_REPLACEMENT("tableView:trailingSwipeActionsConfigurationForRowAtIndexPath:", ios(8.0, 13.0)) API_UNAVAILABLE(tvos);
```
> Mark tableView editActionsForRowAt as deprecated

- Example.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
- Source/Core/RowType.swift
This code should be equivalent but somehow using unowned crashes the app in iOS 13.
Also when building for release the compiler crashes with a segmentation fault.
Fixes #1987 
Fixes #1999 
Fixes #1988
> Unowned self reference crashed on iOS 13

- Source/Rows/Common/FieldRow.swift
> Start editing field rows at the end when tapping blank space in row

- Source/Core/SelectableSection.swift
This PR provides a workaround to the crash affecting Swift 5.3 betas 2 and 3. It replaces a `Self: Section` constraint with two alternate constraints that allow the code to achieve the same result.
Working around bugs in beta compilers isn't always the best approach so I understand if this doesn't get merged. It's mostly an FYI for anyone looking to get around the crash in the meantime.
> Workaround for crash in Swift 5.3 beta 2/3

- Source/Core/Core.swift
This PR makes it possible for subclasses of `FormViewController` to specify a `UITableView.Style` for the form table.
This way, a subclass can specify the style e.g. via the initializer called by UIKit:
```
required init?(coder aDecoder: NSCoder) {
super.init(coder: aDecoder)
tableViewStyle = .plain
}
```
or lets you specify the style in `viewDidLoad`:
```
override func viewDidLoad() {
if #available(iOS 13.0, *) {
self.tableViewStyle = .insetGrouped
}
super.viewDidLoad()
}
```
I needed to be able to set the table view style in `viewDidLoad` to `.insetGrouped` in my project but failed at doing so, because the `tableViewStyle`-property in `FormViewController` is marked as private.
This simply marks the property `tableViewStyle` as `public` instead of `private`.
> Make tableViewStyle public

- .travis.yml
- Eureka.xcodeproj/project.pbxproj
There seems to be an issue in Xcode 12 when building with Carthage. This allows installing Eureka without any additional change
Fixes #2066
> Fix for building with Carthage and Xcode 12

- Source/Core/Core.swift
Hello :wave:
**Context**
The default `tableView.scrollTo` with a `ScrollPosition.none` should animate in a way that the cell is fully visible. It works in most cases, but it seems to fail (scrolls out of view bounds) in the case of a cell preceding a very long footer. Most of the blame here is on Apple side, as I'll show below, however this change request could easily allow to bypass the issue.
**Example/Experiment**
In this commit (https://github.com/lcoderre/Eureka/commit/13c5d65c5f5899bd670267b8729aa0613942f46b) I modified the examples to add a very long Lorem Ipsum footer to a section, and also demonstrated using a pure UITableViewController with scrolling on every cell-click.
👀 - You might notice I recorded this on `iPhone 11 pro` simulator, but I also repeated the test on iPhone 8, …
> Add option for different ScrollPosition behavior on keyboard appearance

- Source/Core/Cell.swift
- Source/Core/Core.swift
- Source/Core/NavigationAccessoryView.swift
Fixes #2109 
Only classes that inherit from AnyObject or any UIKit classes and no generic classes can be namespaced like this
> Prefix Eureka to certain class names to avoid clashes with other pods

- Eureka.xcodeproj/project.pbxproj
Removing `arm64` exclude arch build settings workaround for carthage by https://github.com/xmartlabs/Eureka/pull/2104 to support
- M1 mac
- recently released carthage v0.37 xcframeworks for M1 mac
users that not using xcframeworks can still workaround for carthage by https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md
> support M1 Mac arm64 iPhone Simulator and xcframeworks for carthage

- Source/Core/Form.swift
- Source/Core/Section.swift
- Tests/SectionsInsertionTests.swift
Override the `removeAll(where:)` method as it causes Duplicate Tag errors
Fixes #2048
> Fix removeAll method in sections

- Source/Rows/Common/FieldRow.swift
do nothing if the text field has markedTextRange
> Fix Chinese input issue

- Source/Validations/RuleRegExp.swift
- Tests/ValidationsTests.swift
> Fixes #2159. Specific special characters are allowed in an email address

- .github/workflows/ci.yml
- Source/Core/Cell.swift
- Source/Core/Core.swift
> Fix crash when user taps tab key on external keyboard

- Source/Core/Core.swift
Fix a bug in mac-catalyst because `tableView(_:editActionsForRowAt:)` has been deprecated in iOS 13, ipadOS 13 and **macCatalyst 13.1.**
If we do not add the correct deprecation version, it will create an inconsistency between MacOSX SDK and the library. UITableView's headers are explicitly marked deprecated at 13.1, and the library will take 13 (from iOS) - making a premature deprecation in catalyst.
**Source**: https://developer.apple.com/documentation/uikit/uitableviewdelegate/1614956-tableview
> [Bug] Mac Catalyst: set the correct deprecated version

- Source/Rows/TextAreaRow.swift
on iOS 16, when I tap on a TextAreaRow’s content to start editing, the cursor always goes to the end.
I can reproduce this in Eureka’s sample app. here’s a video:
[opting out of TextKit 2](https://developer.apple.com/videos/play/wwdc2022-10090/?time=643) inside _TextAreaCell’s UITextView resolves the issue.
> fix bug where tapping TextAreaRow always puts the cursor at the end

- Source/Rows/PickerInlineRow.swift
Currently there's no way to configure the way that an DoublePickerInlineRow displays its values in the picker, which is avaliable in DoublePickerRow and DoublePickerInputRow. This pull request addresses that missing feature.
After:
> Add displayValueForFirstRow and displayValueForSecondRow closure in DoublePickerInlineRow

- Source/Validations/RuleRegExp.swift
- Tests/ValidationsTests.swift
The current URL regex has a number of issues, for example, it doesn't match `http://localhost` or `https://example.com:8080`.
The proposed expression is taken from [here](https://stackoverflow.com/a/22648406)
It passes all the validation tests including the newly added ones.
> Improve URL pattern matching

- CHANGELOG.md
- Eureka.podspec
- Eureka.xcodeproj/project.pbxproj
- Eureka.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Example.xcodeproj/project.pbxproj
- README.md
- Source/PrivacyInfo.xcprivacy
> PrivacyInfo
