xmartlabs/Eureka

- README.md
Removes two occurrences of "the the" in README
> Removes duplicated words in README

- Source/Core.swift
- Tests/HiddenRowsTests.swift
> Fix bug when inserting hidden row in midst of a section. closes #54

- Example/Example/ViewController.swift
- Source/Cells.swift
- Source/Core.swift
- Source/Rows.swift
> Added support for PickerView through PickerRow and PickerInlineRow

- Source/Core.swift
This has various advantages, see http://nshint.io/blog/2015/10/23/noescape-attribute/ and http://stackoverflow.com/questions/28427436/noescape-attribute-in-swift-1-2
> Adds @noescape attribute to row initializer closure

- Source/Core.swift
Added convenience initializer for setting table view style.
> Set table view style on init

- README.md
> update README(fix 404)

- Example/Example/ViewController.swift
- Source/Cells.swift
> Fixed currency formatter.

- Source/Rows.swift
I think these semicolons are unnecessary unless adding additional statement after it.
> Delete unnecessary semicolons

- Source/Rows.swift
I have changed the implementation of _ImageRow so that it now ask which source type should be used when sourceTypes property has more then one source type defined.
What do you think of it?
> ImageRow with Action Sheet

- Source/Core.swift
- Source/Helpers.swift
- Source/Rows.swift
> remove uneccessary internal access control

- Eureka.playground/Contents.swift
- Eureka.playground/contents.xcplayground
- Eureka.playground/timeline.xctimeline
Sorry.  Somehow I forgot to create a new branch in my earlier pull request.
> Fixed Playground Deprecation Warning

- Example/Example/ViewController.swift
- Source/Cells.swift
- Source/Core.swift
- Source/Rows.swift
- Tests/BaseEurekaTests.swift
Cleaned up pull request. Replaces the existing pull request https://github.com/xmartlabs/Eureka/pull/171.
> Feature: PostalAddressRow

- Source/Cells.swift
- Source/Rows.swift
Changing type of DecimalRow from Float to Double
> fix issue: DecimalRow formatter wrong for too-big number?

- Source/Cells.swift
Fix crash which occurs durring collapse while picker bounces beyond last value. Resolves issue #208
> Fix crash during PickerInlineRow collapse

- README.md
Adds a code quality badge by codebeat - Swift support has been just added this week. I hope our reports will add some value for Eureka contributors :)
[![codebeat badge](https://codebeat.co/badges/16f29afb-f072-4633-9497-333c6eb71263)](https://codebeat.co/projects/github-com-xmartlabs-eureka)
Disclaimer: I'm a co-author of this tool. We're an early stage product, so please share your feedback. Thanks for your support!
> Update README.md with a code quality badge

- Source/Cells.swift
- Tests/CallbacksTests.swift
> Fixed PostalAddressRow which did not set the value.

- Source/Rows.swift
if it has a value and a property allowImageClear which is Bool and set to true by default.
This is my second attempt at this pull request. This one should work better than last time.
Wasn't really sure if I had to do my own fork to make this work, but here we are :-)
Learning git and github together.
> Adding option to clear ImageRow 

- CHANGELOG.md
- Eureka.podspec
- Example/Example/CustomCells.swift
- README.md
- Source/Core.swift
- Source/Rows.swift
_Alert and _ActionSheet rows also permit custom cell
> Selector row now requires generic cell parameter

- Source/Rows/Common/FieldRow.swift
> Allowed overriding of constraints in FieldRow.

- README.md
> Added missing syntax highlighting in README

- Eureka.xcodeproj/project.pbxproj
- Example/Example/ViewController.swift
- Source/Rows/StepperRow.swift
Implements stepper row and adds an example to the example project. resolves #279
> Stepper Row (#279)

- Source/Core/Core.swift
fix issue https://github.com/xmartlabs/Eureka/issues/395
> fix autolayout in cells

- Example/Example/ViewController.swift
See issue #3. There are only examples of using buttons with segues and it is not immediately clear to use the onCellSelection function.
> Added onCellSelection example

- Source/Rows/Common/FieldRow.swift
Need to make this protocol public in order to be able to use it in the custom inheritors of FieldRow class
> open FieldRowConformance protocol

- Source/Rows/PostalAddressRow.swift
Fix for "filling all the information in a long form, when user scrolls up/down, values in the Address box disappears". For details see https://github.com/xmartlabs/Eureka/issues/423
> Fix for #423

- Source/Core/Form.swift
- Tests/HelperMethodTests.swift
Enables iterating over hidden sections.
> Add allSections method to Form.

- Source/Rows/Controllers/MultipleSelectorViewController.swift
I needed to change the value of title of the row in a MultipleSelectorViewController, but there was no way to do it.
So I addeed a new callback to do this.
Related issue #495
> Added cell setup callback in MultipleSelectorViewController

- Example/UITests/FieldRowUITests.swift
- Tests/BaseEurekaTests.swift
- Tests/CallbacksTests.swift
- Tests/CollectionTests.swift
- Tests/DateTests.swift
- Tests/HelperMethodTests.swift
- Tests/HiddenRowsTests.swift
- Tests/RowCallbackTests.swift
My bad didn't migrate the Test.
Fixed UITest (running but failing)
Fixed Unit Test (migrated everything except 2 errors in HiddenRowsTests.swift which I cannot figure out) Help wanted here
> Test migration for Swift3

- README.md
- Source/Core/Core.swift
- Source/Core/HeaderFooterView.swift
- Source/Core/Helpers.swift
- Source/Rows/PopoverSelectorRow.swift
- Source/Rows/SegmentedRow.swift
Also adapted to new Xcode beta 3.
Still several warnings to be addressed in future.
Not sure why `subPredicates` in `Predicate` are AnyObject and not Predicate's...
> Fixed release configuration

- Source/Rows/Common/FieldRow.swift
- Source/Rows/SegmentedRow.swift
- Source/Rows/TextAreaRow.swift
> fixed alignment for cells if image set

- README.md
> Update presenter example in Readme

- Eureka.playground/Contents.swift
- Eureka.playground/timeline.xctimeline
- Example/Example/CustomCells.swift
- Example/Example/Helpers/FloatLabelTextField.swift
- Example/Example/ViewController.swift
- Example/UITests/FieldRowUITests.swift
- Source/Core/Cell.swift
- Source/Core/Core.swift
- Source/Core/Form.swift
- Source/Core/HeaderFooterView.swift
- Source/Core/Helpers.swift
- Source/Core/NavigationAccessoryView.swift
- Source/Rows/ButtonRow.swift
- Source/Rows/ButtonRowWithPresent.swift
- Source/Rows/Common/DateFieldRow.swift
- Source/Rows/Common/FieldRow.swift
- Source/Rows/Common/GenericMultipleSelectorRow.swift
- Source/Rows/Common/SelectorRow.swift
- Source/Rows/DateRow.swift
- Source/Rows/ImageRow.swift
- Source/Rows/PostalAddressRow.swift
- Source/Rows/SwitchRow.swift
- Source/Rows/TextAreaRow.swift
- Tests/HiddenRowsTests.swift
- Tests/RowCallbackTests.swift
This PR gets the swift3 branch running with tests passing under Xcode 8 beta 5 but seem to time out on travis.
One issue I ran in to is `canBecomeFirstResponder` is now a [read-only property](https://developer.apple.com/reference/uikit/uiresponder/1621130-canbecomefirstresponder
) instead of a method in the latest release. I have commented out the two overrides in the project with a TODO comment.
> Update for Xcode 8 beta 5

- README.md
> Add to formatter documentation

- Source/Rows/SliderRow.swift
displayValueFor not worked for updates of sliderRow
> Fix: displaying new value of slider with displayValueFor

- README.md
> Explain subclassing of cells with nib better

- README.md
Love the project. Glad I could find a way to help, even if so tiny. 💖
> Update SelectionType usages in README to Swift 3

- Source/Validations/RuleLength.swift
- Tests/ValidationsTests.swift
> fix RuleMaxLength & RuleMinLength issues. closes #729.

- Source/Validations/RuleEmail.swift
- Source/Validations/RuleLength.swift
- Source/Validations/RuleRange.swift
- Source/Validations/RuleRequired.swift
- Source/Validations/RuleURL.swift
This PR becomes validation message is customizable
example
```swift
row.add(rule: RuleRequired("customize message"))
```
> Customizable validation message

- Eureka.xcodeproj/project.pbxproj
- Example/Example/ViewController.swift
- Source/Validations/RuleEqualsToRow.swift
#747 - A new rule validation. Compare that two row has the same values. Maybe we should create also a RuleNotEqualsToRow, for the moment, I dont think this is usefull.
> RuleEqualsToRow validation feature

- Source/Rows/DatePickerRow.swift
- Source/Rows/PickerRow.swift
- Source/Rows/StepperRow.swift
- Source/Rows/TextAreaRow.swift
> fixes #693 - Error when compiling CustomRow containing UITextView with Swift 3.0

- README.md
PresentationMode code was changed in version 2.0.0-beta.1
#773
> Fix custom presenter row code example

- Source/Rows/SliderRow.swift
> Fix initialisation of SliderRow when it has no value at start

- Source/Rows/Common/FieldRow.swift
> fix #796 & #768

- Source/Core/BaseRow.swift
- Source/Core/Core.swift
> close #492

- Source/Rows/Common/FieldRow.swift
- Source/Rows/SegmentedRow.swift
If the application wasn't active when the `FormViewController` was displayed (such as if a system permission dialog was currently active), `FieldRow` would observe `titleLabel.text` twice (once in setup and once in the `NSNotification` callback). `FieldRow` would only call `removeObserver` once in `deinit`, which lead to a crash when the underlying label was deallocated and KVO noticed the dangling observation.
Happy to try to reproduce this in a regression test case if you like.
> Fix a crash due to uneven KVO observer calls

- README.md
Or however you think best to do it, it'd be a nice addition to the documentation coverage.
> Adds RuleClosure example in code comments

- Example/Example/CustomCells.swift
Changing keyboardType from .namePhonePad to .asciiCapable.
> Bug fixing NameFloatLabelCell. 

- Example/Example/ViewController.swift
- Source/Core/Form.swift
- Source/Core/Section.swift
- Source/Rows/ButtonRow.swift
- Source/Validations/RuleEqualsToRow.swift
Improvements done:
* Removed retain cycles in example view controllers
* Removed retain cycles in `RuleEqualsToRow` rule
* Cleaned up collections from KVOWrappers
This might solve #974 and #1000
> Fixes memory issues

- README.md
Making it easier for future users to install
> Updated README.md to fix install issue with cocoapods

- Eureka.playground/Contents.swift
Fixes typo in playground instructions view.
> Change FromViewController to FormViewController

- Example/Example/ViewController.swift
- Source/Rows/SegmentedRow.swift
`SegmentedRow` now supports `UIImage` options.
Fixes #840
> Implement UIImage support for SegmentedRow.

- Source/Rows/Controllers/SelectorViewController.swift
This pr fixes the issue when selecting option in single option selector does not clear selection of previous value from another section.
> Fixed single selection for sectioned selector view controller

- Source/Core/Core.swift
- Source/Core/Section.swift
This fixes all compiler warnings from both Eureka and the Example project.
> Fix compiler warnings.

- Example/Example/CustomCells.swift
- Example/Example/ViewController.swift
This PR allows to put image in ImageCheckCell in the accessory view to the right side of the title.
> Added option to use accessory view in ImageCheckCell

- Example/Example/Base.lproj/Main.storyboard
- Example/Example/ViewController.swift
- Source/Core/Form.swift
- Source/Core/Section.swift
- Tests/MultivaluedSectionTests.swift
This is the swift 4 port of #1215
> MultivaluedSection.values() swift4

- Source/Rows/Controllers/MultipleSelectorViewController.swift
- Corrected issue in section sorting function of MultipleSelectorViewController, where all options were placed in one section, with a section title based on the first option
> Fix MultipleSelectorViewController Section Sorting

- Example/Example/Info.plist
- Source/Rows/SliderRow.swift
And set height of SliderRow to automatic
Fixes #1408 
Fixes #1407
> Added NSCameraUsageDescription to Example

- Source/Core/Cell.swift
This reverts commit 7931948c61ac55027e06ce91fb390429179152fa.
Recommended in thread for issue #1447
> Revert "Update cell when tintColor changes"

- Source/Rows/DateInlineRow.swift
- Source/Rows/DateRow.swift
* Localizes countdown strings
* Removes hard coded countdown strings
> Use DateComponentFormatter to format countdown strings

- README.md
> Fix Readme `selectionType`

- Documentation/README_CN.md
- README.md
@mats-claassen Added Chinese readme. https://github.com/xmartlabs/Eureka/issues/1466
> add Chinese readme

- Documentation/README_CN.md
@mats-claassen fixed some issues in Chinese readme.
> fix markdown issues and finish untranslated statement in Chinese readme

- Source/Rows/TextAreaRow.swift
> Fix TextAreaRow placeholder frame

- Source/Core/Cell.swift
- Source/Rows/Common/FieldRow.swift
Fixed a possible crash when receive tintColorDidChange message when the row has already been deleted, but is still animating.
> Fixed a possible crash when receive tintColorDidChange message

- Source/Core/Core.swift
> Fix onCellHighlightChanged in RowDefaults

- Eureka.xcodeproj/project.pbxproj
- Example/Example/Controllers/RowsExample.swift
- Source/Rows/DoublePickerInputRow.swift
- Source/Rows/DoublePickerRow.swift
- Source/Rows/MultiplePickerRow.swift
- Source/Rows/PickerInlineRow.swift
- Source/Rows/PickerInputRow.swift
- Source/Rows/PickerRow.swift
- Source/Rows/TriplePickerInputRow.swift
- Source/Rows/TriplePickerRow.swift
> PickerRow for multiple components

- Source/Core/Core.swift
Fix problem with property showInsertIconInAddButton don't hide plus button in MultivaluedSection
Problem mentioned in  #1135
> Fix problem with property showInsertIconInAddButton

- Source/Rows/SliderRow.swift
> Force SliderRow to add constraints

- Source/Rows/TriplePickerInputRow.swift
- Source/Rows/TriplePickerRow.swift
> Fix crash in TriplePickerRows

- Source/Rows/StepperRow.swift
If you have a long title then set cell.textLabel?.numberOfLines = 0 and set an appropriate height.
> Fix StepperRow title label overlapping stepper

- Source/Rows/TextAreaRow.swift
Screenshot of how the feature works when we set titlePercentage:
> titlePercentage added for textAreaRow

- Source/Rows/TextAreaRow.swift
> Avoid changing global state of animations enabled

- Source/Core/Form.swift
- Source/Core/Section.swift
Having a form with 500 sections and removing all of them would take ~15 seconds because `removeAllObjects` of NSMutableArray was calling the observer for every section it removed. This way the observer is called only once.
> Change `removeAll` implementations to be faster

- Example/Example/Controllers/CustomDesignController.swift
- Source/Rows/Common/FieldRow.swift
> Allow proper subclassing of FieldRow using nib files

- Source/Core/Row.swift
- Source/Core/Validation.swift
- Source/Rows/SegmentedRow.swift
> Allow access to validation rules

- Source/Rows/CheckRow.swift
> Make CheckCell open

- Source/Rows/FieldsRow.swift
Added a couple more UITextContentTypes to FieldRows to build on https://github.com/xmartlabs/Eureka/pull/1698
> Set additional UITextContentTypes to FieldRows

- Example/Example/Controllers/RowsExample.swift
- Source/Rows/StepperRow.swift
Addressing #1838 
I ended up copying the code from SliderRow and adapting it slightly.
One Remark:  I prefer the value label text color  to be grey like in the SliderRow, but I have left it as it was for now.
> Fix StepperRow layout when imageView is set

- Example/Example/Controllers/ValidationsController.swift
- Example/Example/CustomCells.swift
- Example/Example/CustomRows/ImageRow/ImageRow.swift
> Fix crashes due to simultaneous access in examples

- .travis.yml
- Example/Example/Base.lproj/LaunchScreen.storyboard
- Example/Example/Base.lproj/Main.storyboard
- Example/Example/Controllers/RowsExample.swift
- Source/Core/Cell.swift
- Source/Rows/Common/FieldRow.swift
- Source/Rows/PickerInputRow.swift
- Source/Rows/TextAreaRow.swift
Includes:
* Dark mode support (#1889)
* Travis update for Xcode 11
> Updates for Xcode 11 and iOS 13

- Source/Core/NavigationAccessoryView.swift
This also triggered warning that the setter argument was never used.
> Setting the property wouldn't work

- Source/Rows/StepperRow.swift
Changing detailTextLabel to custom self-managed label
Fixes #1910
> Fixed StepperRow for iOS 13

- CHANGELOG.md
- Eureka.podspec
- Eureka.xcodeproj/project.pbxproj
- README.md
- Source/Info.plist
This release contains:
* Support for Xcode 11 and iOS 13
* Added dark mode support
> version bump 5.1.0

- README.md
- Source/Core/Core.swift
- Source/Core/Form.swift
- Source/Core/Section.swift
You can now add any row type as add button.
Fixes #1467 
Fixes #1832 
Addresses #1812
> Add GenericMultivaluedSection to allow changing add button

- Source/Rows/Controllers/SelectorViewController.swift
Solve #1961 
Redundant code is deleted.
> Fix optional header and footer in SelectorViewController.

- Source/Rows/PickerInputRow.swift
> Remove InputTypeInitiable constraint for PickerInputRow

- README.md
> Update min Xcode version in Readme

- Example/Example/Controllers/NativeEventExample.swift
> Fix crash when selecting an Alert on Native iOS Event Form

- Source/Core/Core.swift
> Reload rows on viewWillAppear for iOS 12 and below.

- Source/Core/BaseRow.swift
- Source/Core/Row.swift
These changes are solving [this issue](https://github.com/xmartlabs/Eureka/issues/2038).
> Change validation functions access level to open

- Source/Rows/Common/FieldRow.swift
> Fix subtitle field row constraints

- .travis.yml
- Source/Core/SelectableSection.swift
Workaround crash in Swift 5.3 Xcode 12
> Update SelectableSection.swift (#2061)

- Source/Rows/FieldsRow.swift
> Adjust font size of PasswordRow to avoid dots

- Example/Example/Controllers/RowsExample.swift
- Source/Rows/DatePickerRow.swift
> Fix CountDown rows crash

- Source/Rows/Controllers/SelectorViewController.swift
Now, the section header won't have any default title.
Close #2127
> Remove the default header title of section

- Source/Rows/FieldsRow.swift
> Modify hugging priority for PasswordRow

- Source/Rows/Common/DateFieldRow.swift
- Source/Rows/DatePickerRow.swift
- Source/Rows/SegmentedRow.swift
- Source/Rows/SliderRow.swift
- Source/Rows/StepperRow.swift
- Source/Rows/SwitchRow.swift
ITMS-90338: Non-public API usage valueChanged , datePickerValueChanged
Fixed Apple verification problem when using the latest XCode version to generate and upload Archives to iTunes
> ITMS-90338: Non-public API usage valueChanged , datePickerValueChanged

- Source/Core/Form.swift
This PR adds a new method `Form.replaceSubrangeInAllSections(_:with:)` which replaces a subrange of *all* sections (including hidden ones) with a given set of sections.
In addition, it *replaces* existing visible sections within the subrange by the visible sections in the new element collection.
@mats-claassen Please let me know if you have any concerns.
Resolves #2003
> Add replace method for all sections

- Source/Core/CellType.swift
- Source/Core/Form.swift
- Source/Core/Section.swift
- Source/Rows/Common/DateFieldRow.swift
- Source/Rows/Common/Protocols.swift
> resolve class protocol inheritance warnings

- Source/Rows/SliderRow.swift
> SliderRow not rendering properly

- CHANGELOG.md
- Eureka.podspec
- Eureka.xcodeproj/project.pbxproj
- Eureka.xcodeproj/xcshareddata/xcschemes/Eureka.xcscheme
- Example.xcodeproj/project.pbxproj
- Example.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
- README.md
* Resolve class protocol inheritance warnings (#2151)
* Fix Chinese input issue (#2150) …
* Specific special characters are allowed in the username of an email address (#2160)
* Fix SliderRow not rendering properly (#2166)
> Version bump 5.3.4

- Source/Core/Cell.swift
> Fix responder type

- README.md
> Add documentation comment to Readme

- Source/Core/NavigationAccessoryView.swift
> Fixed done button issue in keyboard

- Source/Rows/Common/DateFieldRow.swift
- Source/Rows/DatePickerRow.swift
- Source/Rows/SegmentedRow.swift
- Source/Rows/SliderRow.swift
- Source/Rows/StepperRow.swift
- Source/Rows/SwitchRow.swift
Methods names were updated to avoid the Payload Warning when try to upload a build to Testflight
> Payload warning
